### ISSUE TITLE
Bug: login插件启用时报错

### ISSUE THREAD

**Issue by CDN18** [koishijs/console#132]
### 环境
- Koishi 4.12.1
- Console 5.5.5
- 从auth插件迁移至login插件：login插件版本3.1.0，使用相同配置。

### 报错
```
2023-03-19 21:17:58 [W] mysql INSERT INTO `user` (`id`, `name`, `flag`, `authority`, `locale`, `lastCall`, `sandbox`, `eula`, `onebot`, `usage`, `timers`, `password`, `token`, `expire`, `github.accessToken`, `github.refreshToken`, `qqguild`) VALUES (0, '***', 0, 5, '', NULL, NULL, false, NULL, '{}', '{}', '*********************************************************36c', '', 0, '', '', NULL) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `authority` = VALUES(`authority`), `password` = VALUES(`password`)
2023-03-19 21:17:58 [W] app ER_BAD_FIELD_ERROR: Unknown column 'sandbox' in 'field list'
                            at MySQLDriver.query (/var/www/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:301:19)
                            at MySQLDriver.upsert (/var/www/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:481:16)
                            at Executable.execute (/var/www/koishi/node_modules/@minatojs/core/lib/index.cjs:384:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async DatabaseService.upsert (/var/www/koishi/node_modules/@minatojs/core/lib/index.cjs:588:5)
                            at async AuthService.start (/var/www/koishi/node_modules/@koishijs/plugin-login/lib/index.js:55:5)
                            at async /var/www/koishi/node_modules/cordis/lib/index.cjs:712:7
```
这个错误导致login插件显示已启用但实际未启用成功，访问面板时不需任何验证。

**Comment by shigma** [comment]
我感觉这个报错跟 login 与 auth 无关。我更新了一下 mysql 版本，你试试新版本是否报错。

如果还报错的话补一下完整的「依赖管理」页面截图或完整的 package.json 文件。
