### ISSUE TITLE
chess插件加载puppeteer报未加载

### ISSUE THREAD

**Issue by jia707409741** [koishijs/console#49]
chess插件加载puppeteer报未加载，启用下列任一插件可实现此服务，但实际puppeteer是处于运行态的，重启也无效

**Comment by jia707409741** [comment]
2022-11-21 13:31:24 [I] app apply plugin chess
2022-11-21 13:31:24 [I] app apply plugin database-sqlite
2022-11-21 13:31:24 [I] app server listening at http://0.0.0.0:5140
2022-11-21 13:31:24 [I] app apply plugin puppeteer
2022-11-21 13:31:24 [W] app Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
                            at ChromeLauncher.launch (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:105:23)
                            at async Puppeteer.start (/koishi/node_modules/koishi-plugin-puppeteer/lib/index.js:50:24)
                            at async /koishi/node_modules/cordis/lib/index.cjs:660:7
                            at async Promise.all (index 16)
                            at async Lifecycle.flush (/koishi/node_modules/cordis/lib/index.cjs:77:7)
                            at async Lifecycle.start (/koishi/node_modules/cordis/lib/index.cjs:163:5)
                            at async start (/koishi/node_modules/@koishijs/cli/lib/worker/index.js:456:3)

**Comment by NWYLZW** [comment]
这个是因为你的环境下面没有安装 chrome 浏览器导致的

提供你的环境信息（虽然已经知道你是 docker 了）

如果是 docker 你需要使用带有 chrome 的 docker 进行迭代，或者自行安装 chrome

如果你是 windows、mac 自己安装一个 chrome 浏览器

如果你是 linux 操作系统，自己在互联网寻找解决方案
